### ISSUE TITLE
Image/Annotation/Error logging error + LAG

### ISSUE THREAD

**Issue by ysjadhav** [changsin/adart#8]
ISSUE 1:
There is a new issue with the way the errors are getting logged.
(Could not repro when a new folder was uploaded)

In the BBox project, the image annotation file for the 0002.jpg image was re-written with the annotation file information for the 0001.jpg image. 
During task review, the first image and the annotations are loaded in normally. 
However, the first image and it's annotations are now being shown in place of the second image and the corresponding annotations as well. 
Images ( and labels) third image onwards are normal. 

Somehow the file itself is being overwritten.

ISSUE 2:
In addition to this, there is a lag in the loading of the images.
When you open up a folder to review in the Review Task option, the image flashes on the screen and then disappears. You have to go to the next image and then come back to see the image and interact with it. 

Similarly there is a slight lag in the loading of the image (and the attributes) when you use the arrow buttons or even through the drop down menu and want to open another image to review. 

![image](https://github.com/changsin/adart/assets/131731374/b30cabde-1ef1-4cbc-b987-de5603c9ac4a)
![image](https://github.com/changsin/adart/assets/131731374/6e008d1a-8810-463a-a73f-8ffea2c19f01)

**Comment by changsin** [comment]
These issues are fixed.
#1. Added a logic to check the filename before overwriting it.
#2. Image flashing is caused by dynamically figuring out the image size based on the window size. Resolved the issue by moving the check outside of the main viewer menu.
